### ISSUE TITLE
Add "delete" and "update" routes and methods. 

### ISSUE THREAD

**Issue by AndrewSC208** [gsd101/realtime-chat-app#1]
DELETE:
Method Name => .deleteMessage( Message_ID )
Http Verb         => Delete
Route               =>  '/messages/:id'
Action              => Remove message with id == Message_ID

UPDATE:
Method Name  => .updateMessage( Message_ID, body)
Http Verb          => Put
Route                => '/messages/:id'
Action               => Update message data, with body data, and id == Message_ID

**Comment by AndrewSC208** [comment]
Delete has been added

**Comment by rakeshsthakur** [comment]
As we discussed that update is not needed for this route, closing this one out.
